DROP TABLE USERS;
CREATE TABLE RIDERS (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100),
    PHONE VARCHAR2(15),
    LOCATION VARCHAR2(100),
    VEHICLE VARCHAR2(50),
    VEHICLE_NUMBER VARCHAR2(20),
    EMAIL VARCHAR2(100),
    PASSWORD VARCHAR2(255)
);



CREATE TABLE bookings (
    booking_id NUMBER PRIMARY KEY,    -- auto-generated ID
    customer_name VARCHAR2(100),
    customer_phone VARCHAR2(15),
    pickup_location VARCHAR2(255),
    destination VARCHAR2(255),
    vehicle_type VARCHAR2(50),
    booking_time TIMESTAMP DEFAULT SYSTIMESTAMP  -- stores date and time with higher precision
);


CREATE SEQUENCE booking_id_seq
START WITH 1
INCREMENT BY 1;

-- Create a trigger to automatically assign the booking_id using the sequence
CREATE OR REPLACE TRIGGER booking_id_trigger
BEFORE INSERT ON bookings
FOR EACH ROW
BEGIN
    -- Assign the next value from the sequence to the booking_id column
    SELECT booking_id_seq.NEXTVAL
    INTO :new.booking_id
    FROM dual;
END;



DROP TABLE bookings CASCADE CONSTRAINTS;

DROP TRIGGER booking_id_trigger;

DROP TRIGGER booking_id_trigger;
SELECT * FROM  BOOKINGS;
SELECT * FROM  RIDERS;

TRUNCATE TABLE BOOKINGS;