

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    age NUMBER
);




CREATE TABLE riders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    phone VARCHAR2(15),
    location VARCHAR2(100),
    vehicle VARCHAR2(50),
    vehicle_number VARCHAR2(50),
    email VARCHAR2(100),
    password VARCHAR2(255) -- Consider hashing passwords before storing
);

CREATE TABLE your_table_name (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100),
    email VARCHAR2(100),
    age NUMBER,
    address VARCHAR2(255),
    phone VARCHAR2(15)
);



SELECT * FROM YOUR_TABLE_NAME;
SELECT * FROM RIDERS;

DROP TABLE your_table_name;